# Generated by Django 6.0.1 on 2026-02-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
